### ISSUE TITLE
Finger allocation

### ISSUE THREAD

**Issue by iandoug** [mw8/white_keyboard_layout#6]
Hi

Is the finger allocation and home key allocation as loaded here, correct? (ANSI version)

http://patorjk.com/keyboard-layout-analyzer/#/load/mtwzdJR0

thanks, Ian

**Comment by mw8** [comment]
Hi Ian,

The layout itself looks correct in terms of key placement, but I think the home keys of the right hand should be shifted one right (SNOI instead of CSNO).

Thanks for comparing the layout.

Cheers,
Michael

**Comment by iandoug** [comment]
Have made the changes, also assigned two keys to left index rather than right index, because they look closer. Are you okay with it now?
http://patorjk.com/keyboard-layout-analyzer/#/load/ZnFMjpxB

Thanks, Ian

**Comment by mw8** [comment]
Sorry for the delay. It looks correct now. Thank you.

**Comment by iandoug** [comment]
Thanks, will use that version in next round of tests ;-)
